# Generated by Django 5.2.1 on 2025-10-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('writer', 'Writer'), ('editor', 'Editor'), ('admin', 'Admin')], default='reader', max_length=20),
        ),
    ]
