# Generated by Django 5.2.1 on 2025-10-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='date_subscribed',
            new_name='created_at',
        ),
    ]
