# Generated by Django 5.2.1 on 2025-11-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_date_subscribed_subscriber_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='article_audio/'),
        ),
    ]
