# Generated by Django 5.2.1 on 2025-11-24 20:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Streams of Faith', max_length=200)),
                ('volume', models.PositiveIntegerField(default=1)),
                ('month', models.CharField(blank=True, max_length=20)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('main_content', models.TextField(help_text='Main writeup of the month')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsletter_images/')),
                ('order', models.PositiveIntegerField(default=1)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='newsletter.newsletter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
