# Generated by Django 5.2.1 on 2025-11-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersection',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link at the bottom of the section', null=True),
        ),
        migrations.AlterField(
            model_name='newslettersection',
            name='content',
            field=models.TextField(blank=True, help_text='You can use HTML here'),
        ),
    ]
