# Generated by Django 5.2.1 on 2025-11-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newslettersection_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='main_content',
            field=models.TextField(help_text='Main writeup of the month (plain text or HTML)'),
        ),
        migrations.AlterField(
            model_name='newslettersection',
            name='content',
            field=models.TextField(blank=True, help_text='You can use HTML here or plain text'),
        ),
        migrations.AlterField(
            model_name='newslettersection',
            name='heading',
            field=models.CharField(blank=True, help_text='Optional section heading', max_length=200, null=True),
        ),
    ]
