# Generated by Django 5.2.1 on 2025-11-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0005_article_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewComment',
            fields=[
            ],
            options={
                'verbose_name': 'New Comment',
                'verbose_name_plural': 'New Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('articles.comment',),
        ),
    ]
